<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class SF_Embed_Admin {
	private $sermon_options;
	private $profile_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'page_init' ) );
	}

	public function add_plugin_page() {
		add_options_page(
			'SoundFaith Embed', // page_title
			'SoundFaith Embed', // menu_title
			'manage_options', // capability
			'soundfaith-embed', // menu_slug
			array( $this, 'create_admin_page' ) // function
		);
	}

	public function create_admin_page() {
		$this->sermon_options = get_option( 'soundfaith_embed_sermon_options' ); 
		$this->profile_options = get_option( 'soundfaith_embed_profile_options' ); ?>

		<div class="wrap">
			<h2>SoundFaith Embed</h2>
			<p>Embed sermons or profiles from SoundFaith.com in your WordPress posts and pages. <br />
			Just paste the URL of the sermon or profile into the post editor and the player will be automagically embedded. <br />
			The embedded player width is controlled by your theme's <code>$content_width</code>.</p>
			<?php //settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'soundfaith_embed_option_group' );
					do_settings_sections( 'soundfaith-embed-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function page_init() {
		register_setting(
			'soundfaith_embed_option_group', // option_group
			'soundfaith_embed_sermon_options', // option_name
			array( $this, 'soundfaith_embed_sermon_sanitize' ) // sanitize_callback
		);

			add_settings_section(
				'soundfaith_embed_sermon_setting_section', // id
				'Sermon Embed Settings', // title
				array( $this, 'sermon_section_info' ), // callback
				'soundfaith-embed-admin' // page
			);

				add_settings_field(
					'includeSermonDetails', // id
					'Show sermon details', // title
					array( $this, 'sermon_includeSermonDetails_callback' ), // callback
					'soundfaith-embed-admin', // page
					'soundfaith_embed_sermon_setting_section' // section
				);

		register_setting(
			'soundfaith_embed_option_group', // option_group
			'soundfaith_embed_profile_options', // option_name
			array( $this, 'soundfaith_embed_profile_sanitize' ) // sanitize_callback
		);

			add_settings_section(
				'soundfaith_embed_profile_setting_section', // id
				'Profile Embed Settings', // title
				array( $this, 'profile_section_info' ), // callback
				'soundfaith-embed-admin' // page
			);

				add_settings_field(
					'includeSermonDetails', // id
					'Show sermon details', // title
					array( $this, 'includeSermonDetails_callback' ), // callback
					'soundfaith-embed-admin', // page
					'soundfaith_embed_profile_setting_section' // section
				);

				add_settings_field(
					'includeThumbnail', // id
					'Show thumbnail in playlist', // title
					array( $this, 'includeThumbnail_callback' ), // callback
					'soundfaith-embed-admin', // page
					'soundfaith_embed_profile_setting_section' // section
				);

				add_settings_field(
					'includeSpeaker', // id
					'Show speaker name in playlist', // title
					array( $this, 'includeSpeaker_callback' ), // callback
					'soundfaith-embed-admin', // page
					'soundfaith_embed_profile_setting_section' // section
				);	
				add_settings_field(
					'includeSeries', // id
					'Show series name in playlist', // title
					array( $this, 'includeSeries_callback' ), // callback
					'soundfaith-embed-admin', // page
					'soundfaith_embed_profile_setting_section' // section
				);	
				add_settings_field(
					'includeDatePresented', // id
					'Show sermon date in playlist', // title
					array( $this, 'includeDatePresented_callback' ), // callback
					'soundfaith-embed-admin', // page
					'soundfaith_embed_profile_setting_section' // section
				);						
	}

	public function soundfaith_embed_sermon_sanitize( $input ) {
		$sanitary_values = array();

		if ( isset( $input['includeSermonDetails'] ) ) {
			$sanitary_values['includeSermonDetails'] = $input['includeSermonDetails'];
		} else {
			$sanitary_values['includeSermonDetails'] = 'false';
		}		

		return $sanitary_values;
	}

	public function soundfaith_embed_profile_sanitize( $input ) {
		$sanitary_values = array();

		$sanitary_values['includePlaylist'] = 'true';

		if ( isset( $input['includeSermonDetails'] ) ) {
			$sanitary_values['includeSermonDetails'] = $input['includeSermonDetails'];
		} else {
			$sanitary_values['includeSermonDetails'] = 'false';
		}

		if ( isset( $input['includeThumbnail'] ) ) {
			$sanitary_values['includeThumbnail'] = $input['includeThumbnail'];
		} else {
			$sanitary_values['includeThumbnail'] = 'false';
		}

		if ( isset( $input['includeSpeaker'] ) ) {
			$sanitary_values['includeSpeaker'] = $input['includeSpeaker'];
		} else {
			$sanitary_values['includeSpeaker'] = 'false';
		}

		if ( isset( $input['includeSeries'] ) ) {
			$sanitary_values['includeSeries'] = $input['includeSeries'];
		} else {
			$sanitary_values['includeSeries'] = 'false';
		}

		if ( isset( $input['includeDatePresented'] ) ) {
			$sanitary_values['includeDatePresented'] = $input['includeDatePresented'];
		} else {
			$sanitary_values['includeDatePresented'] = 'false';
		}

		return $sanitary_values;
	}

	public function sermon_includeSermonDetails_callback() {
		printf(
			'<input type="checkbox" name="soundfaith_embed_sermon_options[includeSermonDetails]" id="includeSermonDetails" value="true" %s>',
			( isset( $this->sermon_options['includeSermonDetails'] ) && $this->sermon_options['includeSermonDetails'] === 'true' ) ? 'checked' : ''
		);
	}

	public function sermon_section_info() {
		echo '<p>These settings will be applied when embedding an individual sermon.</p>';
	}

	public function profile_section_info() {
		echo '<p>These settings will be applied when embedding profiles/playlists.</p>';
		echo '<p><em>Note: It is possible for a profile/playlist URL to change. Use the <code>groupId</code> in your URL to avoid issues.</em></p>';
	}

	public function includeSermonDetails_callback() {
		printf(
			'<input type="checkbox" name="soundfaith_embed_profile_options[includeSermonDetails]" id="includeSermonDetails" value="true" %s>',
			( isset( $this->profile_options['includeSermonDetails'] ) && $this->profile_options['includeSermonDetails'] === 'true' ) ? 'checked' : ''
		);
	}

	public function includeThumbnail_callback() {
		printf(
			'<input type="checkbox" name="soundfaith_embed_profile_options[includeThumbnail]" id="includeThumbnail" value="true" %s>',
			( isset( $this->profile_options['includeThumbnail'] ) && $this->profile_options['includeThumbnail'] === 'true' ) ? 'checked' : ''
		);
	}

	public function includeSpeaker_callback() {
		printf(
			'<input type="checkbox" name="soundfaith_embed_profile_options[includeSpeaker]" id="includeSpeaker" value="true" %s>',
			( isset( $this->profile_options['includeSpeaker'] ) && $this->profile_options['includeSpeaker'] === 'true' ) ? 'checked' : ''
		);
	}	

	public function includeSeries_callback() {
		printf(
			'<input type="checkbox" name="soundfaith_embed_profile_options[includeSeries]" id="includeSeries" value="true" %s>',
			( isset( $this->profile_options['includeSeries'] ) && $this->profile_options['includeSeries'] === 'true' ) ? 'checked' : ''
		);
	}	

	public function includeDatePresented_callback() {
		printf(
			'<input type="checkbox" name="soundfaith_embed_profile_options[includeDatePresented]" id="includeDatePresented" value="true" %s>',
			( isset( $this->profile_options['includeDatePresented'] ) && $this->profile_options['includeDatePresented'] === 'true' ) ? 'checked' : ''
		);
	}		

}