<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class SF_Embed_Admin {
	private $sermon_options;
	private $profile_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'page_init' ) );
	}

	public function add_plugin_page() {
		add_options_page(
			'SoundFaith Embed', // page_title
			'SoundFaith Embed', // menu_title
			'manage_options', // capability
			'soundfaith-embed', // menu_slug
			array( $this, 'create_admin_page' ) // function
		);
	}

	public function create_admin_page() {
		$this->sermon_options = get_option( 'soundfaith_embed_sermon_options' ); 
		$this->profile_options = get_option( 'soundfaith_embed_profile_options' ); ?>

		<div class="wrap">
			<h2>SoundFaith Embed</h2>
			<p>Embed sermons or profiles from SoundFaith.com in your WordPress posts and pages. <br />
			Just paste the URL of the sermon or profile into the post editor and the player will be automagically embedded. <br />
			The embedded player width is controlled by your theme's <code>$content_width</code>.</p>
			<?php //settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'soundfaith_embed_option_group' );
					do_settings_sections( 'soundfaith-embed-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function page_init() {
		register_setting(
			'soundfaith_embed_option_group', // option_group
			'soundfaith_embed_sermon_options', // option_name
			array( $this, 'soundfaith_embed_sermon_sanitize' ) // sanitize_callback
		);

			add_settings_section(
				'soundfaith_embed_sermon_setting_section', // id
				'Sermon Embed Settings', // title
				array( $this, 'sermon_section_info' ), // callback
				'soundfaith-embed-admin' // page
			);

				add_settings_field(
					'sermon_show_sermon_details_0', // id
					'Show sermon details', // title
					array( $this, 'sermon_show_sermon_details_0_callback' ), // callback
					'soundfaith-embed-admin', // page
					'soundfaith_embed_sermon_setting_section' // section
				);

		register_setting(
			'soundfaith_embed_option_group', // option_group
			'soundfaith_embed_profile_options', // option_name
			array( $this, 'soundfaith_embed_profile_sanitize' ) // sanitize_callback
		);

			add_settings_section(
				'soundfaith_embed_profile_setting_section', // id
				'Profile Embed Settings', // title
				array( $this, 'profile_section_info' ), // callback
				'soundfaith-embed-admin' // page
			);

				add_settings_field(
					'show_sermon_details_0', // id
					'Show sermon details', // title
					array( $this, 'show_sermon_details_0_callback' ), // callback
					'soundfaith-embed-admin', // page
					'soundfaith_embed_profile_setting_section' // section
				);

				add_settings_field(
					'show_thumbnail_1', // id
					'Show thumbnail in playlist', // title
					array( $this, 'show_thumbnail_1_callback' ), // callback
					'soundfaith-embed-admin', // page
					'soundfaith_embed_profile_setting_section' // section
				);

				add_settings_field(
					'show_speaker_name_2', // id
					'Show speaker name in playlist', // title
					array( $this, 'show_speaker_name_2_callback' ), // callback
					'soundfaith-embed-admin', // page
					'soundfaith_embed_profile_setting_section' // section
				);	
				add_settings_field(
					'show_series_3', // id
					'Show speaker name in playlist', // title
					array( $this, 'show_series_3_callback' ), // callback
					'soundfaith-embed-admin', // page
					'soundfaith_embed_profile_setting_section' // section
				);	
				add_settings_field(
					'show_date_4', // id
					'Show speaker name in playlist', // title
					array( $this, 'show_date_4_callback' ), // callback
					'soundfaith-embed-admin', // page
					'soundfaith_embed_profile_setting_section' // section
				);						
	}

	public function soundfaith_embed_sermon_sanitize( $input ) {
		$sanitary_values = array();

		if ( isset( $input['sermon_show_sermon_details_0'] ) ) {
			$sanitary_values['sermon_show_sermon_details_0'] = $input['sermon_show_sermon_details_0'];
		} else {
			$sanitary_values['sermon_show_sermon_details_0'] = 'false';
		}		

		return $sanitary_values;
	}

	public function soundfaith_embed_profile_sanitize( $input ) {
		$sanitary_values = array();

		if ( isset( $input['show_sermon_details_0'] ) ) {
			$sanitary_values['show_sermon_details_0'] = $input['show_sermon_details_0'];
		} else {
			$sanitary_values['show_sermon_details_0'] = 'false';
		}

		if ( isset( $input['show_thumbnail_1'] ) ) {
			$sanitary_values['show_thumbnail_1'] = $input['show_thumbnail_1'];
		} else {
			$sanitary_values['show_thumbnail_1'] = 'false';
		}

		if ( isset( $input['show_speaker_name_2'] ) ) {
			$sanitary_values['show_speaker_name_2'] = $input['show_speaker_name_2'];
		} else {
			$sanitary_values['show_speaker_name_2'] = 'false';
		}

		if ( isset( $input['show_series_3'] ) ) {
			$sanitary_values['show_series_3'] = $input['show_series_3'];
		} else {
			$sanitary_values['show_series_3'] = 'false';
		}

		if ( isset( $input['show_date_4'] ) ) {
			$sanitary_values['show_date_4'] = $input['show_date_4'];
		} else {
			$sanitary_values['show_date_4'] = 'false';
		}

		return $sanitary_values;
	}

	public function sermon_show_sermon_details_0_callback() {
		printf(
			'<input type="checkbox" name="soundfaith_embed_sermon_options[sermon_show_sermon_details_0]" id="sermon_show_sermon_details_0" value="true" %s>',
			( isset( $this->sermon_options['sermon_show_sermon_details_0'] ) && $this->sermon_options['sermon_show_sermon_details_0'] === 'true' ) ? 'checked' : ''
		);
	}

	public function sermon_section_info() {
		echo '<p>These settings will be applied when embedding an individual sermon.</p>';
	}

	public function profile_section_info() {
		echo '<p>These settings will be applied when embedding profiles/playlists.</p>';
	}

	public function show_sermon_details_0_callback() {
		printf(
			'<input type="checkbox" name="soundfaith_embed_profile_options[show_sermon_details_0]" id="show_sermon_details_0" value="true" %s>',
			( isset( $this->profile_options['show_sermon_details_0'] ) && $this->profile_options['show_sermon_details_0'] === 'true' ) ? 'checked' : ''
		);
	}

	public function show_thumbnail_1_callback() {
		printf(
			'<input type="checkbox" name="soundfaith_embed_profile_options[show_thumbnail_1]" id="show_thumbnail_1" value="true" %s>',
			( isset( $this->profile_options['show_thumbnail_1'] ) && $this->profile_options['show_thumbnail_1'] === 'true' ) ? 'checked' : ''
		);
	}

	public function show_speaker_name_2_callback() {
		printf(
			'<input type="checkbox" name="soundfaith_embed_profile_options[show_speaker_name_2]" id="show_speaker_name_2" value="true" %s>',
			( isset( $this->profile_options['show_speaker_name_2'] ) && $this->profile_options['show_speaker_name_2'] === 'true' ) ? 'checked' : ''
		);
	}	

	public function show_series_3_callback() {
		printf(
			'<input type="checkbox" name="soundfaith_embed_profile_options[show_series_3]" id="show_series_3" value="true" %s>',
			( isset( $this->profile_options['show_series_3'] ) && $this->profile_options['show_series_3'] === 'true' ) ? 'checked' : ''
		);
	}	

	public function show_date_4_callback() {
		printf(
			'<input type="checkbox" name="soundfaith_embed_profile_options[show_date_4]" id="show_date_4" value="true" %s>',
			( isset( $this->profile_options['show_date_4'] ) && $this->profile_options['show_date_4'] === 'true' ) ? 'checked' : ''
		);
	}		

}
// if ( is_admin() )
	// $soundfaith_embed = new SF_Embed_Admin();

/* 
 * Retrieve this value with:
 * $soundfaith_embed_profile_options = get_option( 'soundfaith_embed_profile_options' ); // Array of All Options
 * $show_sermon_details_0 = $soundfaith_embed_profile_options['show_sermon_details_0']; // Show sermon details
 * $show_thumbnail_1 = $soundfaith_embed_profile_options['show_thumbnail_1']; // Show thumbnail in playlist
 */
